"""
Quiz Repository.
Manages Quizzes, QuizQuestions, and QuizAttempts with user isolation.
"""

import uuid
from typing import List, Optional
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.database.models.quiz import Quiz, QuizAttempt, QuizQuestion
from backend.database.repositories.base import BaseRepository


class QuizRepository(BaseRepository[Quiz]):
    """Quiz repository."""

    def __init__(self, session: AsyncSession):
        super().__init__(Quiz, session)

    async def get_user_quizzes(self, user_id: uuid.UUID) -> List[Quiz]:
        """Fetches quizzes generated by user."""
        return await self.get_multi(user_id=user_id)

    async def get_quiz_with_questions(
        self, quiz_id: uuid.UUID, user_id: uuid.UUID
    ) -> Optional[Quiz]:
        """Fetches a quiz with eager loaded questions for a user."""
        query = (
            select(Quiz)
            .where(Quiz.id == quiz_id)
            .where(Quiz.user_id == user_id)
            .where(Quiz.is_deleted == False)
        )
        result = await self.session.execute(query)
        return result.scalars().first()

    async def record_quiz_attempt(
        self, quiz_id: uuid.UUID, user_id: uuid.UUID, score: float, delta_theta: float
    ) -> QuizAttempt:
        """Records a user's quiz attempt submission."""
        attempt = QuizAttempt(
            quiz_id=quiz_id,
            user_id=user_id,
            score_percentage=score,
            delta_theta=delta_theta,
        )
        self.session.add(attempt)
        await self.session.flush()
        await self.session.refresh(attempt)
        return attempt
